name: "Airport Checkin"

on:
  schedule:
    - cron: "30 22 * * *"  # scheduled at 06:30 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-100 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sign
        env:
          SCKEY: ${{ secrets.SCKEY }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
        run: |
          python ./main.py
